name: tabler
description: This library is displaying tabular data in ASCII table format.
version: 1.0.2
homepage: https://github.com/yuzumone/tabler

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  wcwidth: ^0.0.4

dev_dependencies:
  pedantic: ^1.10.0
  test: ^1.16.0
