name: tabler
description: This library is displaying tabular data in ASCII table format.
version: 1.1.0
repository: https://github.com/yuzumone/tabler

environment:
  sdk: '>=2.12.0 <4.0.0'

dependencies:
  wcwidth: ^0.0.4

dev_dependencies:
  lints: ^2.1.1
  test: ^1.16.0
